### ISSUE TITLE
installation faild!

### ISSUE THREAD

**Issue by N-studio18fr** [forkbb/forkbb#12]
hi, i just try to install forkbb on my wamp serveur, but when i use your explication to install, I'hav an error !

`PHP OTHER_ERROR: Class "Normalizer" not found in ...\app\Core\Secury.php:[107]

Trace:

    ...\app\Core\Validator.php(296): ForkBB\Core\Secury->replInvalidChars(string)
    ...\app\Core\Validator.php(259): ForkBB\Core\Validator->__get(string)
    ...\app\Models\Pages\Admin\Install.php(89): ForkBB\Core\Validator->validation(array(20))
    ...\app\Controllers\Install.php(59): ForkBB\Models\Pages\Admin\Install->install(array(0), string)
    ...\app\Core\Container.php(117): ForkBB\Controllers\Install->routing()
    ...\app\bootstrap.php(85): ForkBB\Core\Container->__get(string)
    ...\index.php(14): require(string)`

que dois je faire pour réussir l'installation? j'aimerai participer au projet si celui ci est toujours d'actualité!

Good job Visman ! :)

**Comment by MioVisman** [comment]
Enable intl extension for php.

**Comment by N-studio18fr** [comment]
impossible even with the extension activated to run it on my mamp .... (on windows...) suddenly I have .htaccess a folder on one of my hosting and managed to install it!

The time to understand how github works and I will see to create an fr branch of forkbb! on your advice (message from your N-studio forum) I will resume fr support or at least try to reactivate it concerning fluxbb, so that those who are still running on old versions can have their security updated!

could I contact you by mail to solve some problems that I have with the lang pack that I created for flux?

then start developing one for forkbb?

it would be a shame if you stopped your work is so clean!

**Comment by MioVisman** [comment]
I get this error if I disable the intl extension in the php config.
Create file 1.php in localhost

```
<?php
phpinfo();

```

And open http://localhost/1.php in browser.
The opened page should have information about the intl extension:
![intl](https://user-images.githubusercontent.com/5917956/218069349-252adaaf-36cf-4d64-8ec2-fd54a06f2f14.png)


You can write to: mio.visman(just a doggy)gmail.com
But if you use github, it is more convenient to create forks, pull requests, issues. So the information will not be lost until github erases everything.

In French for FluxBB, the issue was raised here https://github.com/MioVisman/FluxBB_by_Visman/issues/20
Maybe @finkiki did something, but I don't have the information.

**Comment by N-studio18fr** [comment]
Google translate:

Thank you for your answer!

For the installation, I went through the free host at least it worked, I started an Fr language pack for ForkBB (25% to all, intsall 100%)!

I'm thinking of starting to look at sources for UX and theme!

For the fr fluxbb pack, I only have two documents left to translate, but after testing, when I use the pack, bugs appear on the forum ( example, impossible to register for the forum under the lang fr pack ==> blank page)

I paused this translation not knowing if it would be usable and where the problem comes from, I don't know if it causes other problems...

I'm going to look at the issue you are telling me about!

Thank you and see you soon ;)
